apiVersion: v1
kind: Service
metadata:
  name: email-verifier-blue-svc
spec:
  type: ClusterIP
  selector:
    app: email-verifier
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000