apiVersion: v1
kind: Service
metadata:
  name: email-verifier-green
  namespace: email-verifier
spec:
  selector:
    app: email-verifier
    version: green
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP 
