apiVersion: v1
kind: Service
metadata:
  name: email-verifier-green-svc
spec:
  type: ClusterIP
  selector:
    app: email-verifier
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000